repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: requirements-txt-fixer

-   repo: https://github.com/PyCQA/pylint
    rev: v2.17.4
    hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score
        ]

-   repo: https://github.com/PyCQA/doc8
    rev: v1.1.1
    hooks:
    - id: doc8
