version: '3.8'
services:
  web:
    container_name: matchups
    restart: always
    env_file: apps/.env
    build: .
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - web
  db:
    container_name: postgres
    restart: always
    image: "postgres:15"
    env_file: apps/.env
    logging:
          options:
            max-size: 10m
            max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts/1_users.sql:/docker-entrypoint-initdb.d/1_users.sql 
      - ./scripts/2_dummy_tables.sql:/docker-entrypoint-initdb.d/3_dummy_tables.sql 
    networks:
      - web_network
    depends_on: 
      - web
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
volumes:
  db-data:
 
