version: '3.8'
services:
  app:
    container_name: matchups_app
    restart: always
    env_file: .env
    build: .
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - app
  database:
    container_name: postgres
    restart: always
    image: "postgres:15"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts/db/tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./scripts/db/dummy_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
      - ./scripts/db/users.sql:/docker-entrypoint-initdb.d/create_users.sql
    networks:
      - web_network
    depends_on: 
      - app
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
volumes:
  db-data:
 
